version: '2.4'
services:
 app:
  image: flaskex:v1 
  command: python3 app.py
  depends_on: 
   - database
  ports: 
   - "3000:5000"
  environment:
   DATABASE_URL: 172.10.1.2  

  networks:
   db-network:
    ipv4_address: 172.10.1.2 
 database:
  image: sqlite:v1
  volumes:
   - "./local-db:/db"
  networks:
   db-network:
    ipv4_address: 172.17.1.16
  restart: always
networks:
 db-network:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 172.10.1.0/24
     
