version: '2.4'
services:
 app:
  image: flaskex:v1 
  command: python3 app.py
  depends_on: 
   - database
  ports: 
   - "3000:5000"
  environment:
   DATABASE_URL: 10.0.0.15  

  networks:
   db-network:
    ipv4_address: 10.0.0.8 
 database:
  image: sqlite:v1
  volumes:
   - "./local-db:/db"
  networks:
   db-network:
    ipv4_address: 10.0.0.15
  restart: always
networks:
 db-network:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 10.0.0.0/16
    #ip_range: 10.0.0.0/128
    gateway: 10.0.0.1
     
