version: '2.4'
services:
 app:
  image: flaskex:v1 
  command: python3 app.py
  depends_on: 
   - database
  ports: 
   - "3000:5000"
  environment:
   DATABASE_URL: 173.17.0.2  

  networks:
   db-network:
    ipv4_address: 173.17.0.3 
 database:
  image: sqlite:v1
  volumes:
   - "./local-db:/db"
  networks:
   db-network:
    ipv4_address: 173.17.0.2
  restart: always
networks:
 db-network:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 173.17.0.0/16
    - gateway: 173.17.0.1
     
